buxlabs/boxwood

test/spec/features/filters.js

This change depends on:
[https://github.com/buxlabs/pure-utilities/pull/58](url)

added tests for new 'ltrim' filter from pure-utilities

---

package-lock.json
package.json
src/action.js
test/spec/tags/if.js

closes #320 and closes #321 and closes #323 and closes #324  and closes #325 andl closes #326 and closes #327 and closes #328 and closes #329

New.actions

---

src/files.js
src/node.js
src/plugins/InlinePlugin.js
src/tags/font.js
test/spec/tags/font.js
test/spec/tags/style.js

Support for shorthand syntax

---

src/Importer.js
src/Linter.js
src/node.js
test/spec/tags/img.js

Fixed warnings for inlined images and svgs

---

src/Compiler.js
src/collect.js
src/convert.js
src/errors.js
src/filters.js
src/plugins/InternationalizationPlugin.js
src/validation.js
test/spec/compiler.js

Errors.stack

---

src/collect.js
src/scope.js
test/spec/tags/script/scoped.js

Add to scope object only used properties

---

src/translations.js
test/fixtures/translations/attributes/qux.html
test/spec/features/i18n.js

Marked Identifier node as inlined

---

src/Component/curlyTagReduction.js
test/spec/features/filters.js

Filters.in.partials

---

src/Compiler.js
src/collect.js
src/enum.js
src/tags/spacing.js
src/validation.js
test/spec/compiler.js
test/spec/tags/spacing.js

Spacing.tag

---

package-lock.json
package.json
src/filters.js
test/spec/features/i18n.js

Dynamic.translations

---

src/factory.js
test/spec/tags/for.js

Better.dynamic.range

---

README.md
test/spec/features/filters.js
test/spec/tags/for.js

Specs.object.keys

---

src/collect.js
src/enum.js
src/tags/space.js
test/spec/tags/space.js

Added space tag

---

test/spec/tags/style.js

closes #406 
I added only few specs because this issue was fixed some time ago

Added few specs for attribute selectors

---

test/spec/output.js

Added specs

---

src/convert.js
src/plugins/InternationalizationPlugin.js
src/translations.js
test/spec/features/filters.js
test/spec/features/i18n.js

Allows using filters in translation

---

src/collect.js
test/spec/tags/img.js

Fixed fluid attr

---

src/collect.js
test/spec/features/attributes.js

Support shorthand attributes syntax on components

---

src/collect.js
src/enum.js
src/tags/entity.js
test/spec/tags/entity.js

Added entity tag. Handled most common entities

---

src/collect.js
src/plugins/ScopedStylesPlugin.js
src/tags/default.js
src/tags/index.js
test/spec/tags/style.js

Fix scoped styles for classes within expressions

---

src/plugins/InlinePlugin.js
test/spec/tags/style/inline.js

Do not throw on split

---

README.md
src/tags/index.js
src/tags/translate.js
src/utilities/collect.js
src/utilities/enum.js
src/utilities/translations.js
test/fixtures/translations/scoped/nested/index.html
test/spec/features/i18n.js

Translate with slots

---

src/utilities/collect.js
test/spec/acceptance.js
test/spec/features/i18n.js
test/spec/features/import.js

Allow to import components within a partial

---

src/Component/curlyTagReduction.js
src/utilities/collect.js
src/utilities/inline.js
test/fixtures/acceptance/admin-page/actual.html
test/fixtures/acceptance/admin-page/components/layout.html
test/fixtures/acceptance/app-page/actual.html
test/fixtures/acceptance/app-page/layouts/layout.html
test/fixtures/acceptance/explicit-variables/actual.html
test/fixtures/acceptance/explicit-variables/data.json
test/fixtures/acceptance/explicit-variables/expected.html
test/fixtures/acceptance/explicit-variables/layouts/default.html
test/fixtures/acceptance/explicit-variables/layouts/partials/footer.html
test/fixtures/acceptance/explicit-variables/layouts/partials/header.html
test/spec/acceptance.spec.js
test/spec/features/import.spec.js
test/spec/tags/include.spec.js
test/spec/tags/partial.spec.js

Explicit partial properties

---

src/utilities/collect.js
src/utilities/convert.js
src/utilities/options.js
src/utilities/string.js
src/utilities/string.spec.js
test/helpers/compile.js
test/spec/features/compact.spec.js

Compact on demand

---

src/Component/curlyTagReduction.js
src/utilities/collect.js
src/utilities/inline.js
src/utilities/inline.spec.js
test/fixtures/acceptance/styleguide/actual.html
test/fixtures/acceptance/styleguide/components/header.html
test/fixtures/acceptance/styleguide/data.json
test/fixtures/acceptance/styleguide/expected.html
test/fixtures/acceptance/styleguide/layouts/default.html
test/fixtures/acceptance/styleguide/partials/content.html
test/spec/acceptance.spec.js
test/spec/tags/for.spec.js

Inlining arrays

---

src/tags/for.js
src/tags/foreach.js
src/utilities/inline.js
src/utilities/string.js
test/fixtures/acceptance/styleguide/components/header.html
test/fixtures/acceptance/styleguide/data.json
test/fixtures/acceptance/styleguide/expected.html
test/fixtures/acceptance/styleguide/partials/content.html

Closes #595 
Ended up just manipulating the attributes.

Better value inlining

---

src/Scope.js
src/utilities/globals.js
src/utilities/optimize.js
test/fixtures/acceptance/globals/actual.html
test/fixtures/acceptance/globals/data.json
test/fixtures/acceptance/globals/expected.html
test/fixtures/acceptance/globals/layouts/default.html
test/spec/acceptance.spec.js

Better globals support

---

src/plugins/RoutesPlugin.js
test/spec/features/routes.spec.js

Better error handling when script[routes] is used but routes are not set up yet

---

src/tags/script.js
test/spec/tags/script/compiler/async.spec.js

Simplify how script is added for a compiled output

---

src/tags/script.js
test/spec/tags/script/basic.spec.js

script[src] bugfix
